name: Build the main branch and deploy it to beta.habrasanta.org
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run build
        env:
          NODE_ENV: production
      - name: Deploy!
        run: |
          mkdir ~/.ssh
          echo "${{vars.SSH_KNOWN_HOSTS}}" > ~/.ssh/known_hosts
          eval `ssh-agent`
          echo "${{secrets.SSH_PRIVATE_KEY}}" | ssh-add -
          rsync --recursive --verbose dist/ github@rocket.habrasanta.org:/var/www/beta.habrasanta.org
