name: Lint
on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
permissions:
  contents: read
  deployments: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.domain }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - run: |
          mkdir ~/.ssh
          echo "${{ vars.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          eval `ssh-agent`
          echo "$SSH_PRIVATE_KEY" | ssh-add -
          rsync --recursive --verbose dist/ github@rocket.habrasanta.org:/var/www/${{ inputs.domain }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  smoke_test:
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check if the URL is accessible
        run: curl --fail https://${{ inputs.domain }}
