name: Deploy to habra-adm.ru
on:
  push:
    branches:
      - main
concurrency:
  group: deployment
  cancel-in-progress: false
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  build:
    uses: ./.github/workflows/build.yaml
  deploy_staging:
    needs:
      - lint
      - build
    uses: ./.github/workflows/build.yaml
    with:
      domain: beta.habrasanta.org
      environment: staging
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  deploy_production:
    needs:
      - deploy_staging
    uses: ./.github/workflows/build.yaml
    with:
      domain: habra-adm.ru
      environment: production
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
