name: Deploy to habra-adm.ru
on:
  push:
    branches:
      - main
concurrency:
  group: deployment
  cancel-in-progress: false
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  build:
    uses: ./.github/workflows/build.yaml
  deploy_production:
    needs:
      - lint
      - build
    uses: ./.github/workflows/build.yaml
    with:
      domain: habra-adm.ru
      environment: habra-adm.ru
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
