name: Deploy to pull-request-*.habrasanta.org
on:
  pull_request:
concurrency:
  group: pull-request-${{ github.event.number }}-deployment
  cancel-in-progress: true
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  build:
    uses: ./.github/workflows/build.yaml
  deploy:
    needs:
      - lint
      - build
    uses: ./.github/workflows/deploy.yaml
    with:
      domain: pull-request-${{ github.event.number }}.habrasanta.org
      environment: pull-request-${{ github.event.number }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
